package = load_json(json_path: "./package.json")

before_all do
    ensure_git_branch(branch: 'android-main')
    ensure_git_status_clean
    git_pull
end

platform :android do
    desc "Android build and release to beta / release"
    lane :beta do
        package_name("mindsgn.studio.music")
        increment_version_code(gradle_file_path: "./android/app/build.gradle")
        increment_version_name(gradle_file_path: "./android/app/build.gradle", version_name: package['version'])
        gradle(task: 'clean', project_dir: './android/')
        gradle(task: 'bundle', build_type: 'Release', project_dir: './android')
        supply(json_key: "./play-store-credentials.json",  track: 'beta', aab: './android/app/build/outputs/bundle/release/app-release.aab')
    end

    lane :release do
        json_key_file("./play-store-credentials.json")
        package_name("mindsgn.studio.music")
        increment_version_code(gradle_file_path: "./android/app/build.gradle")
        increment_version_name(gradle_file_path: "./android/app/build.gradle", version_name: package['version'])
        gradle(task: 'clean', project_dir: './android/')
        gradle(task: 'bundle', build_type: 'Release', project_dir: './android')
        supply(track: 'release', aab: './android/app/build/outputs/bundle/release/app-release.aab')
    end
end